[package]
name = "ALDS1_1_D_Maximum_Profit"
version = "0.1.0"
authors = ["seitamuro <seitamuro0210@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.3"
