[package]
name = "abc208"
version = "0.1.0"
authors = ["mokeshi3 <mokeshi34649@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = { version = "0.3.6", features = ["derive"] }
itertools = "0.9.0"

[profile.release]
lto = true
panic = 'abort'
